// actionTypes.js
export const ADD_ALL_COURSES = 'ADD_ALL_COURSES';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const UPDATE_ALL_COURSES = 'UPDATE_ALL_COURSES';
export const GET_COURSES_LIST = 'GET_COURSES_LIST';
export const ADD_TO_COURSES_LIST = 'ADD_TO_COURSES_LIST';
export const UPDATE_COURSES_LIST = 'UPDATE_COURSES_LIST';
export const SHOW_COURSES_LIST = 'SHOW_COURSES_LIST';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const UPDATE_ONE_COURSE = 'UPDATE_ONE_COURSE';
